[versions]
spring-boot = '3.2.0'
spring-boot-dependancy-management = "1.1.4"
[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-boot-dependency = { id = "io.spring.dependency-management", version.ref = "spring-boot-dependancy-management" }